# Generated by Django 4.2.5 on 2023-10-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('email', models.TextField(blank=True)),
                ('Subject', models.TextField(blank=True)),
            ],
        ),
    ]
