# Generated by Django 4.2.5 on 2023-10-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='option',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Subject',
            field=models.IntegerField(blank=True),
        ),
    ]
