# Generated by Django 4.2.5 on 2023-10-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_option_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='option',
            field=models.IntegerField(default='anything'),
        ),
    ]
