# Generated by Django 4.2.5 on 2023-10-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contact_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='option',
            field=models.IntegerField(default='anything', max_length=15),
        ),
    ]
