# Generated by Django 4.2.5 on 2023-10-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_contact_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Subject',
            new_name='subject',
        ),
    ]
